ready for review
vladimirakulchik/magento_insurance_module pull request #1
Opened 2018-01-30 06:59 UTC by vladimirakulchik

Magento task

2018-01-31 08:08 UTC, v-matsuk requested changes
В целом по коду неплохо. Есть некоторые замечание по именованию констант + одно дополнительное требование. Давай немного видоизменим твое задание. Мы делали включение страховки на том же шаге, что и выбор метода доставки и подписывались вот на соответсвтующий ивент. Давай теперь заведем для страховки доставки отдельный шаг, который будет идти следом за выбором метода доставки.

2018-01-31 08:08 UTC, v-matsuk commented on Insurance/app/code/local/Itransition/Insurance/Helper/Data.php
> +    const PERCENT = 100;
Во первых, название константы ничего не говорит о том, зачем она нужна. Во вторых, из контекста будет очевидно, зачем ты делишь на 100. Т.е. конатанта не нужна эта

2018-01-31 08:08 UTC, v-matsuk commented on Insurance/app/code/local/Itransition/Insurance/Helper/Data.php
> +        return $state === self::ENABLE;
По всему коду, перед return ставь пустую строчку. Лучше читается. Исключение только если в предыдущей строчке есть  знак { (начало метода, первая строчка в цикле, условии)
Здесь тебе не нужна перемеменная. Правильнее было бы сравнить вызов методата с константой

2018-01-31 08:08 UTC, v-matsuk commented on Insurance/app/code/local/Itransition/Insurance/Helper/Data.php
> +    const ENABLE = '1';
ENABLED

2018-01-31 08:08 UTC, v-matsuk commented on Insurance/app/code/local/Itransition/Insurance/Helper/Data.php
> +    const DISABLE = '0';
DISABLED

2018-01-31 08:08 UTC, v-matsuk commented on Insurance/app/code/local/Itransition/Insurance/Helper/Data.php
> +    const ENABLED = '/enabled';
CONF_PATH_ENABLED.  - так сразу будет поянтно, что это за константа. Аналогично надо переименовать и другие

2018-01-31 08:08 UTC, v-matsuk commented on Insurance/app/code/local/Itransition/Insurance/Helper/Data.php
> +        switch ($type) {
Ставь пустую строку перед началом цикла/условия. Исключения такие же как и у return

2018-01-31 08:08 UTC, v-matsuk commented on Insurance/app/code/local/Itransition/Insurance/Helper/Data.php
> +        return $insurance != null;
!==

2018-01-31 08:08 UTC, v-matsuk commented on Insurance/app/code/local/Itransition/Insurance/Model/Source/Type.php
> +    const ABSOLUTE_TYPE = 0;
Для таких целей лучше заводить цфры кроме 0. 0 может интерпретироваться как ложное, null тоже интерпретируется как ложное. Но null мы можем юзать, например когда тив не выбран/не определен. И в такой  ситуации при нестрогом сравнении он совпадет с ABSOLUTE. Поэтому, 1 и 2 лучше

2018-02-07 13:29 UTC, vladimirakulchik commented
Готово

2018-02-08 05:38 UTC, merged

2018-02-14 12:43 UTC, v-matsuk commented on Insurance/app/code/local/Itransition/Insurance/Block/Checkout/Onepage.php
> +        $stepCodes = array('billing', 'shipping', 'shipping_method', 'customstep', 'payment', 'review');
Что произойдет, если какой-то сторонний модуль добавит свой степ?

2018-02-14 12:43 UTC, v-matsuk commented on Insurance/app/code/local/Itransition/Insurance/Block/Checkout/Onepage/Customstep.php
> +                'label'     => Mage::helper('insurance')->__('Insurance'),
не надо эти отступы делать

2018-02-14 12:43 UTC, v-matsuk commented on Insurance/app/code/local/Itransition/Insurance/controllers/OnepageController.php
> +                $result['goto_section'] = 'payment';
что, если какой-то модуль добавит свой шаг перед payment? Получается, что после твоего шага он сразу попадет на 'payment'

2018-02-14 12:43 UTC, v-matsuk commented on Insurance/app/code/local/Itransition/Insurance/controllers/OnepageController.php
> +                $result['goto_section'] = 'customstep';
Название для секции хреновое. Не отражает сути